# Generated by Django 5.2.13 on 2026-04-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('industry', models.CharField(blank=True, max_length=50, verbose_name='所属行业')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='企业规模')),
                ('description', models.TextField(blank=True, verbose_name='企业简介')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='企业地址')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='企业官网')),
            ],
            options={
                'verbose_name': '企业',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('role', models.CharField(choices=[('seeker', '求职者'), ('hr', '企业HR'), ('admin', '管理员')], max_length=10, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': '投递记录'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': '简历'},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='apply_time',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='experience',
            new_name='work_exp',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='expected_job',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.resume', verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '待查看'), ('viewed', '已查看'), ('interview', '面试'), ('rejected', '不合适'), ('hired', '录用')], default='pending', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='工作城市'),
        ),
        migrations.AddField(
            model_name='job',
            name='degree_required',
            field=models.CharField(blank=True, max_length=20, verbose_name='学历要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='exp_required',
            field=models.CharField(blank=True, max_length=50, verbose_name='经验要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='工作类型'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(default=0, verbose_name='最高薪资'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(default=0, verbose_name='最低薪资'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_required',
            field=models.TextField(blank=True, verbose_name='技能要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已发布'), ('rejected', '已拒绝'), ('offline', '已下线')], default='pending', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='resume',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='推荐用拼接文本'),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree',
            field=models.CharField(blank=True, max_length=20, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_exp',
            field=models.TextField(blank=True, verbose_name='教育经历'),
        ),
        migrations.AddField(
            model_name='resume',
            name='expect_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='期望城市'),
        ),
        migrations.AddField(
            model_name='resume',
            name='expect_job',
            field=models.CharField(blank=True, max_length=100, verbose_name='期望岗位'),
        ),
        migrations.AddField(
            model_name='resume',
            name='expect_salary',
            field=models.CharField(blank=True, max_length=50, verbose_name='期望薪资'),
        ),
        migrations.AddField(
            model_name='resume',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='resume',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='resume',
            name='school',
            field=models.CharField(blank=True, max_length=100, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='resume',
            name='self_intro',
            field=models.TextField(blank=True, verbose_name='自我评价'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.job', verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='职位描述'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, verbose_name='技能描述'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.company', verbose_name='所属企业'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.user', verbose_name='HR账号'),
        ),
        migrations.AddField(
            model_name='job',
            name='hr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.user', verbose_name='发布HR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.user', verbose_name='求职者'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.user', verbose_name='求职者'),
        ),
    ]
