# Generated by Django 5.2.13 on 2026-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_company_user_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certificate_exp',
            field=models.TextField(blank=True, verbose_name='证书与校园经历'),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_exp',
            field=models.TextField(blank=True, verbose_name='项目经历'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_exp',
            field=models.TextField(blank=True, verbose_name='实习或工作经历'),
        ),
    ]
