# Generated by Django 5.2.13 on 2026-04-15 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_resume_certificate_exp_resume_project_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否当前启用'),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='默认简历', max_length=100, verbose_name='简历名称'),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='recruitment.user', verbose_name='求职者'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_exp',
            field=models.TextField(blank=True, verbose_name='工作经历'),
        ),
    ]
